"use client";

import { useState } from "react";
import { GitPullRequest, Loader2, ExternalLink, AlertCircle } from "lucide-react";

interface Recommendation {
  id: string;
  title: string;
  description?: string | null;
  rationale?: string | null;
  implementation_steps?: string | null;
  priority: string;
  category: string;
  estimated_hours?: number | null;
  impact_score?: number | null;
  affected_files?: string[] | null;
  before_code?: string | null;
  after_code?: string | null;
}

interface Props {
  rec: Recommendation;
  repoUrl: string;
  accessToken: string;
}

function parseRepo(repoUrl: string): { owner: string; repo: string } | null {
  try {
    const url = new URL(repoUrl);
    const parts = url.pathname.replace(/^\//, "").replace(/\/$/, "").split("/");
    if (parts.length >= 2) return { owner: parts[0], repo: parts[1] };
  } catch {}
  return null;
}

function buildPRBody(rec: Recommendation): string {
  const lines: string[] = [];

  lines.push(`## AI Recommendation: ${rec.title}`);
  lines.push("");

  const meta: string[] = [`**Priority:** ${rec.priority}`, `**Category:** ${rec.category}`];
  if (rec.estimated_hours) meta.push(`**Effort:** ~${rec.estimated_hours}h`);
  if (rec.impact_score) meta.push(`**Impact:** ${rec.impact_score}/10`);
  lines.push(meta.join(" | "));
  lines.push("");

  if (rec.description) {
    lines.push("### Description");
    lines.push(rec.description);
    lines.push("");
  }

  if (rec.rationale) {
    lines.push("### Why This Matters");
    lines.push(rec.rationale);
    lines.push("");
  }

  if (rec.implementation_steps) {
    lines.push("### Implementation Steps");
    lines.push(rec.implementation_steps);
    lines.push("");
  }

  if (rec.affected_files && rec.affected_files.length > 0) {
    lines.push("### Affected Files");
    rec.affected_files.forEach((f) => lines.push(`- \`${f}\``));
    lines.push("");
  }

  const hasRealCode =
    rec.before_code &&
    rec.after_code &&
    !rec.after_code.includes("AI generation pending") &&
    !rec.after_code.includes("Refactored code —");

  if (hasRealCode) {
    lines.push("### Before");
    lines.push("```");
    lines.push(rec.before_code!);
    lines.push("```");
    lines.push("");
    lines.push("### After");
    lines.push("```");
    lines.push(rec.after_code!);
    lines.push("```");
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by [CodeLens AI](https://legacy-modernization-platform.vercel.app)*");

  return lines.join("\n");
}

async function createGitHubPR(
  owner: string,
  repo: string,
  token: string,
  rec: Recommendation
): Promise<string> {
  const headers = {
    Authorization: `Bearer ${token}`,
    Accept: "application/vnd.github+json",
    "Content-Type": "application/json",
    "X-GitHub-Api-Version": "2022-11-28",
  };

  const repoRes = await fetch(`https://api.github.com/repos/${owner}/${repo}`, { headers });
  if (!repoRes.ok) throw new Error(`Repo not found (${repoRes.status})`);
  const repoData = await repoRes.json();
  const defaultBranch: string = repoData.default_branch;

  const refRes = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/git/ref/heads/${defaultBranch}`,
    { headers }
  );
  if (!refRes.ok) throw new Error(`Could not read branch ref (${refRes.status})`);
  const refData = await refRes.json();
  const sha: string = refData.object.sha;

  const shortId = rec.id.replace(/-/g, "").substring(0, 8);
  const branchName = `codelens/fix-${shortId}`;

  const createBranch = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/git/refs`,
    {
      method: "POST",
      headers,
      body: JSON.stringify({ ref: `refs/heads/${branchName}`, sha }),
    }
  );
  if (!createBranch.ok) {
    const err = await createBranch.json().catch(() => ({}));
    throw new Error(err.message || `Branch creation failed (${createBranch.status})`);
  }

  // GitHub requires at least one commit between base and head to open a PR.
  // Create a markdown file on the branch summarising the recommendation.
  const filePath = `.codelens/${branchName.replace("codelens/", "")}.md`;
  const fileContent = btoa(unescape(encodeURIComponent(buildPRBody(rec))));
  const fileRes = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/contents/${filePath}`,
    {
      method: "PUT",
      headers,
      body: JSON.stringify({
        message: `fix: ${rec.title} [skip ci]`,
        content: fileContent,
        branch: branchName,
      }),
    }
  );
  if (!fileRes.ok) {
    const err = await fileRes.json().catch(() => ({}));
    throw new Error(err.message || `Commit creation failed (${fileRes.status})`);
  }

  const prRes = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/pulls`,
    {
      method: "POST",
      headers,
      body: JSON.stringify({
        title: `fix: ${rec.title}`,
        body: buildPRBody(rec),
        head: branchName,
        base: defaultBranch,
      }),
    }
  );
  if (!prRes.ok) {
    const err = await prRes.json().catch(() => ({}));
    throw new Error(err.message || `PR creation failed (${prRes.status})`);
  }
  const prData = await prRes.json();
  return prData.html_url as string;
}

export default function CreatePRButton({ rec, repoUrl, accessToken }: Props) {
  const [state, setState] = useState<"idle" | "loading" | "done" | "error">("idle");
  const [prUrl, setPrUrl] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const parsed = parseRepo(repoUrl);
  if (!parsed) return null;

  async function handleClick() {
    if (state === "done" && prUrl) {
      window.open(prUrl, "_blank", "noopener,noreferrer");
      return;
    }
    setState("loading");
    setError(null);
    try {
      const url = await createGitHubPR(parsed!.owner, parsed!.repo, accessToken, rec);
      setPrUrl(url);
      setState("done");
    } catch (err) {
      setError(err instanceof Error ? err.message : "PR creation failed");
      setState("error");
    }
  }

  if (state === "done" && prUrl) {
    return (
      <a
        href={prUrl}
        target="_blank"
        rel="noopener noreferrer"
        className="inline-flex items-center gap-1.5 rounded-lg bg-green-500/10 border border-green-500/30 px-3 py-1.5 text-xs font-medium text-green-500 hover:bg-green-500/20 transition-colors"
      >
        <GitPullRequest className="h-3.5 w-3.5" />
        View PR
        <ExternalLink className="h-3 w-3" />
      </a>
    );
  }

  if (state === "error") {
    return (
      <div className="flex items-center gap-2 flex-wrap">
        <span className="inline-flex items-center gap-1 text-xs text-destructive">
          <AlertCircle className="h-3.5 w-3.5 shrink-0" />
          {error}
        </span>
        <button
          onClick={handleClick}
          style={{ cursor: "pointer" }}
          className="text-xs text-muted-foreground hover:text-foreground underline"
        >
          Retry
        </button>
      </div>
    );
  }

  return (
    <button
      onClick={handleClick}
      disabled={state === "loading"}
      style={{ cursor: state === "loading" ? "default" : "pointer" }}
      className="inline-flex items-center gap-1.5 rounded-lg border border-border px-3 py-1.5 text-xs font-medium text-muted-foreground hover:border-primary hover:text-primary transition-colors disabled:opacity-50"
    >
      {state === "loading" ? (
        <Loader2 className="h-3.5 w-3.5 animate-spin" />
      ) : (
        <GitPullRequest className="h-3.5 w-3.5" />
      )}
      {state === "loading" ? "Creating PR…" : "Create Fix PR"}
    </button>
  );
}
