/**
 * Landing Page
 * ============
 * Public marketing page with hero section, features, and CTA.
 * Server Component — no client-side JavaScript needed.
 */

import Link from "next/link";
import {
  GitBranch,
  Shield,
  BarChart3,
  Zap,
  Bot,
  FileCode2,
  ArrowRight,
  ChevronRight,
} from "lucide-react";

const FEATURES = [
  {
    icon: GitBranch,
    title: "Repository Ingestion",
    description: "Connect any GitHub repository — public or private — via OAuth in seconds.",
  },
  {
    icon: FileCode2,
    title: "AST-Powered Analysis",
    description: "Deep structural analysis using tree-sitter across Python, JavaScript, TypeScript, and Java.",
  },
  {
    icon: BarChart3,
    title: "Technical Debt Scoring",
    description: "Quantified debt metrics with severity scoring across 6 categories.",
  },
  {
    icon: Shield,
    title: "Dependency Risk Detection",
    description: "Automated CVE scanning, version lag tracking, and deprecation alerts.",
  },
  {
    icon: Bot,
    title: "AI Recommendations",
    description: "Prioritized modernization roadmaps generated by Claude and GPT-4.",
  },
  {
    icon: Zap,
    title: "AI Refactoring",
    description: "On-demand code refactoring suggestions with before/after diffs.",
  },
];

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-background">
      {/* ── Navigation ──────────────────────────────────────────────── */}
      <nav className="fixed top-0 z-50 w-full glass">
        <div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-6">
          <div className="flex items-center gap-2">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg gradient-primary">
              <FileCode2 className="h-4 w-4 text-white" />
            </div>
            <span className="text-lg font-bold">CodeLens AI</span>
          </div>
          <div className="flex items-center gap-4">
            <Link
              href="/login"
              className="rounded-lg px-4 py-2 text-sm font-medium text-muted-foreground transition-colors hover:text-foreground"
            >
              Sign In
            </Link>
            <Link
              href="/login"
              className="rounded-lg gradient-primary px-5 py-2 text-sm font-semibold text-white transition-all hover:opacity-90 hover:shadow-lg"
            >
              Get Started
            </Link>
          </div>
        </div>
      </nav>

      {/* ── Hero Section ────────────────────────────────────────────── */}
      <section className="relative flex min-h-screen items-center justify-center overflow-hidden px-6 pt-16">
        {/* Background gradient orbs */}
        <div className="pointer-events-none absolute inset-0 overflow-hidden">
          <div className="absolute -left-40 -top-40 h-[500px] w-[500px] rounded-full bg-primary/10 blur-[100px]" />
          <div className="absolute -bottom-40 -right-40 h-[500px] w-[500px] rounded-full bg-accent/10 blur-[100px]" />
        </div>

        <div className="relative z-10 mx-auto max-w-4xl text-center animate-[fade-in_0.8s_ease-out]">
          <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/10 px-4 py-1.5 text-sm font-medium text-primary">
            <Zap className="h-3.5 w-3.5" />
            AI-Powered Legacy Modernization
          </div>
          <h1 className="mb-6 text-5xl font-extrabold leading-tight tracking-tight md:text-7xl">
            Modernize your{" "}
            <span className="gradient-text">legacy codebase</span>{" "}
            with AI
          </h1>
          <p className="mx-auto mb-10 max-w-2xl text-lg text-muted-foreground md:text-xl">
            Analyze repositories, detect technical debt, identify outdated
            dependencies, and get AI-generated modernization recommendations —
            all in minutes, not weeks.
          </p>
          <div className="flex flex-col items-center justify-center gap-4 sm:flex-row">
            <Link
              href="/login"
              className="group inline-flex items-center gap-2 rounded-xl gradient-primary px-8 py-3.5 text-base font-semibold text-white shadow-lg shadow-primary/25 transition-all hover:shadow-xl hover:shadow-primary/30"
            >
              Start Analyzing
              <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" />
            </Link>
            <Link
              href="#features"
              className="inline-flex items-center gap-2 rounded-xl border border-border px-8 py-3.5 text-base font-semibold transition-colors hover:bg-muted"
            >
              See How It Works
              <ChevronRight className="h-4 w-4" />
            </Link>
          </div>

          {/* Score mockup */}
          <div className="mt-16 flex items-center justify-center gap-6 animate-[slide-up_1s_ease-out_0.3s_both]">
            {[
              { label: "Code Health", score: 72, color: "text-success" },
              { label: "Modernization Score", score: 45, color: "text-warning" },
              { label: "Dependency Risk", score: 28, color: "text-destructive" },
            ].map((item) => (
              <div
                key={item.label}
                className="glass rounded-xl px-6 py-4 text-center card-hover"
              >
                <div className={`text-3xl font-bold ${item.color}`}>
                  {item.score}
                </div>
                <div className="mt-1 text-xs text-muted-foreground">
                  {item.label}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Features ────────────────────────────────────────────────── */}
      <section id="features" className="relative px-6 py-24">
        <div className="mx-auto max-w-6xl">
          <div className="mb-16 text-center">
            <h2 className="mb-4 text-3xl font-bold md:text-4xl">
              Everything you need to{" "}
              <span className="gradient-text">modernize</span>
            </h2>
            <p className="mx-auto max-w-2xl text-muted-foreground">
              From repository analysis to AI-powered recommendations,
              CodeLens AI gives your team the complete picture.
            </p>
          </div>

          <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
            {FEATURES.map((feature, i) => (
              <div
                key={feature.title}
                className="group glass rounded-xl p-6 card-hover"
                style={{ animationDelay: `${i * 100}ms` }}
              >
                <div className="mb-4 inline-flex rounded-lg bg-primary/10 p-3">
                  <feature.icon className="h-5 w-5 text-primary" />
                </div>
                <h3 className="mb-2 text-lg font-semibold">{feature.title}</h3>
                <p className="text-sm leading-relaxed text-muted-foreground">
                  {feature.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── CTA ─────────────────────────────────────────────────────── */}
      <section className="px-6 py-24">
        <div className="mx-auto max-w-4xl text-center">
          <div className="glass rounded-2xl p-12 glow-border">
            <h2 className="mb-4 text-3xl font-bold">
              Ready to modernize?
            </h2>
            <p className="mb-8 text-muted-foreground">
              Connect your GitHub account and get your first analysis in
              under 5 minutes.
            </p>
            <Link
              href="/login"
              className="inline-flex items-center gap-2 rounded-xl gradient-primary px-8 py-3.5 text-base font-semibold text-white shadow-lg shadow-primary/25 transition-all hover:shadow-xl"
            >
              Get Started — It&apos;s Free
              <ArrowRight className="h-4 w-4" />
            </Link>
          </div>
        </div>
      </section>

      {/* ── Footer ──────────────────────────────────────────────────── */}
      <footer className="border-t border-border px-6 py-8">
        <div className="mx-auto flex max-w-7xl items-center justify-between">
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <FileCode2 className="h-4 w-4" />
            CodeLens AI — Built for HyKr Build Challenge 2026
          </div>
          <div className="text-sm text-muted-foreground">
            © {new Date().getFullYear()} CodeLens AI
          </div>
        </div>
      </footer>
    </div>
  );
}
